[tool.isort]
profile = "black"
known_cardpicker = "cardpicker"
known_src = "src"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "CARDPICKER", "SRC", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["build", "dist", "cards"]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
ignore-init-module-imports = true

# Never enforce `E501` (line length violations).
ignore = ["E501"]

# Ignore `E402` (import violations) and `F403` (error from `import *`) in all `__init__.py` files
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F403"]
