name: Formatting and static type checking
on:
  push:
    branches: ["*"]
  workflow_dispatch:
jobs:
  test-backend:
    name: Formatting and static type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-pre-commit
